spring:
  application:
    name: employee-service

  datasource:
    url: jdbc:mysql://localhost:3306/employeeservice
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
   bootstrap-servers: localhost:9092
   consumer:
        group-id: employee-service
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.trusted.packages: '*'
          spring.json.value.default.type: com.ucv.es.dto.EmployeeCreatedEvent
          spring.json.type.mapping: com.ucv.us.dto.EmployeeCreatedEvent:com.ucv.es.dto.EmployeeCreatedEvent


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

user:
  service:
    url: http://localhost:8083

logging:
  level:
    root: INFO
    com.ucv.es: DEBUG

server:
  port: 8085

management:
  endpoints:
    web:
      exposure: "*"
  endpoint:
    health:
      show-details: always
