

# Include full exception details in error responses
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

logging:
  # Keep your own code at DEBUG, everything else at INFO+
  level:
    root: INFO
    com.ucv.us: DEBUG

    # Silence Kafka metrics spam
    org.apache.kafka: WARN
    org.apache.kafka.clients.consumer.internals.KafkaMetricsCollector: WARN

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userservice
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: user-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.value.default.type: com.ucv.us.dto.CandidateCreatedEvent

users:
  topics:
    candidate: candidates-topic
    employee: employees-topic
