server:
  port: 8087

spring:
  application:
    name: matching-service

candidate:
  service:
    url: http://localhost:8084

employee:
  service:
    url: http://localhost:8085

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

management:
  endpoints:
    web:
      exposure: "*"
