server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/users/**
          filters:
            - AddRequestHeader=X-Gateway-Auth, true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
  security:
    enabled: false
